---
- name: Ensure VM is present and running
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhv_vmname }}"
    state: running
    template: "{{ rhv_template }}"
    cluster: "{{ rhv_cluster }}"
    storage_domain: "{{ rhv_stodom }}"
    memory: "{{ rhv_vm_memory }}"
    cpu_cores: "{{ rhv_vm_cpucores }}"
    cpu_sockets: "{{ rhv_vm_cpusockets }}"
    comment: "{{ rhv_vm_comment }}"
    wait: true
    nics:
      - name: "{{ rhv_vm_nic }}"
        profile_name: "{{ rhv_vm_nic_prof }}"
    cloud_init:
      host_name: "{{ rhv_vmname }}"
      user_name: "{{ rhv_vm_username }}"
      root_password: "{{ rhv_vm_pwd }}"
      nic_name: "{{ rhv_vm_nic }}"
      nic_boot_protocol: static
      nic_ip_address: "{{ rhv_vm_ip }}"
      nic_gateway: "{{ rhv_vm_gw }}"
      nic_netmask: "{{ rhv_vm_subnet }}"
      nic_on_boot: "{{ rhv_vm_nic_onboot | default(true) }}"
      dns_servers: "{{ rhv_vm_dns_ip }}"
      dns_search: "{{ rhv_vm_dns_search }}"
  register: r_deploy_rhv

- name: "Wait Until {{ rhv_vmname }} is UP and Running"
  wait_for_connection:
    delay: 60
  delegate_to: localhost

- name: "Add {{ rhv_vmname }} to In-Memory Inventory"
  add_host:
    name: "{{ rhv_vmname }}"
    groups:
      - "{{ r_deploy_rhv.vm.comment }}"
      - just_created
