---
- name: Obtain SSO Token
  ovirt_auth:
    username: "{{ lookup('env','OVIRT_USERNAME') }}"
    password: "{{ lookup('env','OVIRT_PASSWORD') }}"
    url: "{{ lookup('env','OVIRT_URL') }}"
    insecure: true
#    ca_file: "{{ lookup('env','OVIRT_CAFILE') }}"
    state: present

- name: Deploy VM on RHV
  include_tasks: deploy_rhv_vm.yml
  when: rhv_action == "deploy"

- name: Destroy VM on RHV
  include_tasks: destroy_rhv_vm.yml
  when: rhv_action == "destroy"

- name: Revoke SSO Token
  ovirt_auth:
    ovirt_auth: "{{ ovirt_auth }}"
    state: absent
